FROM openjdk:17-jdk-alpine

LABEL maintainer="William Martin Chavez Gonzalez"

COPY target/poc-grpc-project-1.0-SNAPSHOT.jar poc-grpc-project-1.0-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","/poc-grpc-project-1.0-SNAPSHOT.jar"]