apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: poc-grpc-deployment
    spec:
      selector:
        matchLabels:
          app: poc-grpc-project-1.0
      template:
        metadata:
          labels:
            app: poc-grpc-project-1.0
        spec:
          containers:
            - name: poc-grpc-project
              image: poc-grpc-project-1.0:1.1.0-beta
              ports:
                - containerPort: 50052

  - apiVersion: v1
    kind: Service
    metadata:
      name: poc-grpc-service
    spec:
      type: NodePort
      ports:
        - name: grpc
          port: 50052
          targetPort: 50052
          nodePort: 30007
      selector:
        app: poc-grpc-project-1.0